# Generated by Django 4.2.1 on 2023-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.CharField(choices=[('$45,000-60,000', 'Jr. Entry Level'), ('$60,000-70,000', 'Entry Level'), ('$70,000-80,000', 'Intermediate'), ('$80,000-95,000', 'Mid-level'), ('$95,000-110,000', 'Experienced'), ('$110,000 +', 'Senior')], default='$45,000-60,000'),
        ),
    ]
