# Generated by Django 4.2.1 on 2023-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_role_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pub_date',
            field=models.DateField(verbose_name='date added'),
        ),
    ]
