# Generated by Django 4.2.1 on 2023-05-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_role_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='date contacted')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.role')),
            ],
        ),
    ]
