# Generated by Django 4.2.1 on 2023-05-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-date']},
        ),
    ]
