# Generated by Django 4.2.1 on 2023-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_followup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='followup',
            name='contact',
            field=models.CharField(max_length=30, verbose_name='contact info'),
        ),
        migrations.AddField(
            model_name='role',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
