# Generated by Django 4.2.1 on 2023-05-18 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default='(include a link!)', max_length=3000),
        ),
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.CharField(default='$', max_length=100),
        ),
    ]
