# Generated by Django 4.2.1 on 2023-05-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_tag_user_alter_role_description_alter_role_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default='(include a link!)'),
        ),
    ]
