# Generated by Django 4.2.1 on 2023-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default='(include a link!)', max_length=3000),
        ),
    ]
